[package]
name = "puppet_vs_gizmo"
version = "0.12.0"
cairo-version = "2.8.4"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.1" }